//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SteamAuthenticator.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SteamAuthenticator.Properties.strings", typeof(strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloaded! Install now?.
        /// </summary>
        internal static string BackEndUpdateManDownloaded {
            get {
                return ResourceManager.GetString("BackEndUpdateManDownloaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Steam Authenticator Updater.
        /// </summary>
        internal static string BackEndUpdateManDownloadedT {
            get {
                return ResourceManager.GetString("BackEndUpdateManDownloadedT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while extracting updater!.
        /// </summary>
        internal static string BackEndUpdateManErrorExtracting {
            get {
                return ResourceManager.GetString("BackEndUpdateManErrorExtracting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string BackendUpdateManErrorT {
            get {
                return ResourceManager.GetString("BackendUpdateManErrorT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update {0} is currently available! (You&apos;re using {1}).
        /// </summary>
        internal static string BackEndUpdateManNewUpdate {
            get {
                return ResourceManager.GetString("BackEndUpdateManNewUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New update available.
        /// </summary>
        internal static string BackEndUpdateManNewUpdateT {
            get {
                return ResourceManager.GetString("BackEndUpdateManNewUpdateT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available updates.
        /// </summary>
        internal static string BrowseUpdateAvailable {
            get {
                return ResourceManager.GetString("BrowseUpdateAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info.
        /// </summary>
        internal static string BrowseUpdateInfo {
            get {
                return ResourceManager.GetString("BrowseUpdateInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install.
        /// </summary>
        internal static string BrowseUpdateInstall {
            get {
                return ResourceManager.GetString("BrowseUpdateInstall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string btnCancel {
            get {
                return ResourceManager.GetString("btnCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        internal static string btnExit {
            get {
                return ResourceManager.GetString("btnExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        internal static string btnRefresh {
            get {
                return ResourceManager.GetString("btnRefresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skip.
        /// </summary>
        internal static string btnSkip {
            get {
                return ResourceManager.GetString("btnSkip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        internal static string btnSubmit {
            get {
                return ResourceManager.GetString("btnSubmit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the following captcha code:.
        /// </summary>
        internal static string CaptchaEnter {
            get {
                return ResourceManager.GetString("CaptchaEnter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloaded {0} MB(s) of {1} MB(s) ({2}%)
        ///{3} KB/s.
        /// </summary>
        internal static string DownloaderDownloadInfo {
            get {
                return ResourceManager.GetString("DownloaderDownloadInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account not found inside manifest.json.
        ///Import failed..
        /// </summary>
        internal static string ImportAccountNotFound {
            get {
                return ResourceManager.GetString("ImportAccountNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account imported..
        /// </summary>
        internal static string ImportComplete {
            get {
                return ResourceManager.GetString("ImportComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your encryption passkey if your .maFile is encrypted.
        /// </summary>
        internal static string ImportEnterPasskey {
            get {
                return ResourceManager.GetString("ImportEnterPasskey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid content inside manifest.json!
        ///Import failed..
        /// </summary>
        internal static string ImportFailedEncrypted {
            get {
                return ResourceManager.GetString("ImportFailedEncrypted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decyrption failed thus the import failed..
        /// </summary>
        internal static string ImportFailedEncryptedD {
            get {
                return ResourceManager.GetString("ImportFailedEncryptedD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This file is not a valid SteamAuth maFile!
        ///Import failed.
        ///{0}.
        /// </summary>
        internal static string ImportInvaildMaFile {
            get {
                return ResourceManager.GetString("ImportInvaildMaFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid SteamID!.
        /// </summary>
        internal static string ImportInvaildSteamID {
            get {
                return ResourceManager.GetString("ImportInvaildSteamID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to manifest.json does not contain: {0}
        ///Import failed..
        /// </summary>
        internal static string ImportMissingEncryptionData {
            get {
                return ResourceManager.GetString("ImportMissingEncryptionData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to manifest.json is missing!
        ///Import failed..
        /// </summary>
        internal static string ImportMissingManifest {
            get {
                return ResourceManager.GetString("ImportMissingManifest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to manifest.json does not contain encrypted data.
        ///Your account may be unencrypted.
        ///Import failed..
        /// </summary>
        internal static string ImportNoEncryptionData {
            get {
                return ResourceManager.GetString("ImportNoEncryptionData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you import an encrypted file, the manifest must be next to it.
        /// </summary>
        internal static string ImportNotice {
            get {
                return ResourceManager.GetString("ImportNotice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select .maFile to import.
        /// </summary>
        internal static string ImportSelect {
            get {
                return ResourceManager.GetString("ImportSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select your maFile.
        /// </summary>
        internal static string ImportSelectT {
            get {
                return ResourceManager.GetString("ImportSelectT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account imported, but now your account is decrypted..
        /// </summary>
        internal static string ImportSuccessD {
            get {
                return ResourceManager.GetString("ImportSuccessD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select one, or click cancel..
        /// </summary>
        internal static string ListSelectionPick {
            get {
                return ResourceManager.GetString("ListSelectionPick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This account already has a mobile authenticator linked to it.
        ///Remove the old authenticator from your Steam account before adding a new one..
        /// </summary>
        internal static string LoginAleadLinked {
            get {
                return ResourceManager.GetString("LoginAleadLinked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error logging in: Username or password was incorrect..
        /// </summary>
        internal static string LoginBadCreds {
            get {
                return ResourceManager.GetString("LoginBadCreds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error logging in: Steam returned &quot;BadRSA.&quot;.
        /// </summary>
        internal static string LoginBadRSA {
            get {
                return ResourceManager.GetString("LoginBadRSA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the Steam Guard code sent to your email..
        /// </summary>
        internal static string LoginEnterEmailCode {
            get {
                return ResourceManager.GetString("LoginEnterEmailCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter an encryption passkey. Leave blank or hit cancel to not encrypt..
        /// </summary>
        internal static string LoginEnterPasskey {
            get {
                return ResourceManager.GetString("LoginEnterPasskey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your phone number in the following format: +{cC} phoneNumber. EX: +1 555-555-555. (Please note Steam no longer accepts VOIP phone numbers).&quot;.
        /// </summary>
        internal static string LoginEnterPhoneNumber {
            get {
                return ResourceManager.GetString("LoginEnterPhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter your revocation code to ensure you&apos;ve saved it..
        /// </summary>
        internal static string LoginEnterRevocation {
            get {
                return ResourceManager.GetString("LoginEnterRevocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please input the SMS code sent to your phone..
        /// </summary>
        internal static string LoginEnterSMS {
            get {
                return ResourceManager.GetString("LoginEnterSMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error adding your phone number. Steam returned &quot;GeneralFailure.&quot;.
        /// </summary>
        internal static string LoginErrorAddingNumber {
            get {
                return ResourceManager.GetString("LoginErrorAddingNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login Error.
        /// </summary>
        internal static string LoginErrorT {
            get {
                return ResourceManager.GetString("LoginErrorT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field is required..
        /// </summary>
        internal static string LoginFieldRequired {
            get {
                return ResourceManager.GetString("LoginFieldRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error logging in:Steam returned &quot;GeneralFailure.&quot; (Did you use a VOIP number?).
        /// </summary>
        internal static string LoginGeneralFailure {
            get {
                return ResourceManager.GetString("LoginGeneralFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This will activate Steam Authenticator on your Steam account. This requires a (non VOIP) phone number that can receive SMS messages..
        /// </summary>
        internal static string LoginInfo {
            get {
                return ResourceManager.GetString("LoginInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to That passkey is invalid, please enter your current passkey used to encrypt your other accounts..
        /// </summary>
        internal static string LoginInvaildPasskey {
            get {
                return ResourceManager.GetString("LoginInvaildPasskey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your login session was refreshed..
        /// </summary>
        internal static string LoginRefreshedSession {
            get {
                return ResourceManager.GetString("LoginRefreshedSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This will relog in to your Steam account, which usually fixes trade issues..
        /// </summary>
        internal static string LoginRefreshInfo {
            get {
                return ResourceManager.GetString("LoginRefreshInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Revocation code incorrect. Mobile authenticator has not been linked..
        /// </summary>
        internal static string LoginRevocationIncorrect {
            get {
                return ResourceManager.GetString("LoginRevocationIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile authenticator successfully linked! (Revocation code: {0}).
        /// </summary>
        internal static string LoginSuccessfulAdd {
            get {
                return ResourceManager.GetString("LoginSuccessfulAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error logging in: Too many failed logins, try again later..
        /// </summary>
        internal static string LoginTooManyFailedAttempts {
            get {
                return ResourceManager.GetString("LoginTooManyFailedAttempts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to finalize this authenticator. The authenticator should not have been linked, but in the off-chance it was, please write down the revocation code: {0}.
        /// </summary>
        internal static string LoginUnableToFinalize {
            get {
                return ResourceManager.GetString("LoginUnableToFinalize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to generate the proper codes to finalize this authenticator. The authenticator should not have been linked, but in the off-chance it was, please write down the revocation code: {0}.
        /// </summary>
        internal static string LoginUnableToGenerateCodes {
            get {
                return ResourceManager.GetString("LoginUnableToGenerateCodes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to save mobile authenticator file, your account has not been linked..
        /// </summary>
        internal static string LoginUnableToSaveFile {
            get {
                return ResourceManager.GetString("LoginUnableToSaveFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The mobile authenticator has not yet been linked. Before finalizing the authenticator, please write down your revocation code: {0}.
        /// </summary>
        internal static string LoginWriteRevocation {
            get {
                return ResourceManager.GetString("LoginWriteRevocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto Entry.
        /// </summary>
        internal static string MainWindowAutoEntry {
            get {
                return ResourceManager.GetString("MainWindowAutoEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto entry has been disabled..
        /// </summary>
        internal static string MainWindowAutoEntryDisabled {
            get {
                return ResourceManager.GetString("MainWindowAutoEntryDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto entry has been enabled..
        /// </summary>
        internal static string MainWindowAutoEntryEnabled {
            get {
                return ResourceManager.GetString("MainWindowAutoEntryEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Steam Guard.
        /// </summary>
        internal static string MainWindowDeactivateAccount {
            get {
                return ResourceManager.GetString("MainWindowDeactivateAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Steam Guard was not removed, and no action was taken..
        /// </summary>
        internal static string MainWindowDeactivateAccountCanceled {
            get {
                return ResourceManager.GetString("MainWindowDeactivateAccountCanceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Would you like to remove Steam Guard completely?
        ///Yes - Remove Steam Guard completely.
        ///No - Switch back to Email authentication..
        /// </summary>
        internal static string MainWindowDeactivateAccountConfirm {
            get {
                return ResourceManager.GetString("MainWindowDeactivateAccountConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No - Switch back to Email authentication..
        /// </summary>
        internal static string MainWindowDeactivateAccountConfirmNo {
            get {
                return ResourceManager.GetString("MainWindowDeactivateAccountConfirmNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes - Remove Steam Guard completely..
        /// </summary>
        internal static string MainWindowDeactivateAccountConfirmYes {
            get {
                return ResourceManager.GetString("MainWindowDeactivateAccountConfirmYes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Steam Guard failed to deactivate..
        /// </summary>
        internal static string MainWindowDeactivateAccountFailed {
            get {
                return ResourceManager.GetString("MainWindowDeactivateAccountFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removing Steam Guard from {0}. Please enter this confirmation code: {1}.
        /// </summary>
        internal static string MainWindowDeactivateAccountRemoveConfirm {
            get {
                return ResourceManager.GetString("MainWindowDeactivateAccountRemoveConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmation codes do not match. Steam Guard was not removed..
        /// </summary>
        internal static string MainWindowDeactivateAccountRemoveConfirmFailed {
            get {
                return ResourceManager.GetString("MainWindowDeactivateAccountRemoveConfirmFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Steam Guard switched to email. Your maFile will be deleted after hitting okay, (now would be the time to create a backup)..
        /// </summary>
        internal static string MainWindowDeactivateAccountSuccessEmail {
            get {
                return ResourceManager.GetString("MainWindowDeactivateAccountSuccessEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Steam Guard was removed completely. Your maFile will be deleted after hitting okay, (now would be the time to create a backup)..
        /// </summary>
        internal static string MainWindowDeactivateAccountSuccessRemoved {
            get {
                return ResourceManager.GetString("MainWindowDeactivateAccountSuccessRemoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Populating accounts list.
        /// </summary>
        internal static string MainWindowLoadAccountsPopulating {
            get {
                return ResourceManager.GetString("MainWindowLoadAccountsPopulating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account 0/{0}.
        /// </summary>
        internal static string MainWindowLoadAccountsPopulatingAccount0 {
            get {
                return ResourceManager.GetString("MainWindowLoadAccountsPopulatingAccount0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account {0}/{1}.
        /// </summary>
        internal static string MainWindowLoadAccountsPopulatingAccountX {
            get {
                return ResourceManager.GetString("MainWindowLoadAccountsPopulatingAccountX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Populating the account listbox, please wait..
        /// </summary>
        internal static string MainWindowPopulateAccounts {
            get {
                return ResourceManager.GetString("MainWindowPopulateAccounts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove from manifest.
        /// </summary>
        internal static string MainWindowRemoveAccountManifest {
            get {
                return ResourceManager.GetString("MainWindowRemoveAccountManifest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} was removed from your manifest file. Again, you are still able to import the account using it&apos;s maFile..
        /// </summary>
        internal static string MainWindowRemoveAccountManifestComplete {
            get {
                return ResourceManager.GetString("MainWindowRemoveAccountManifestComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This will remove {0} from your manifest file. This will not delete your maFile, and you can add the account back at anytime..
        /// </summary>
        internal static string MainWindowRemoveAccountManifestConfirm {
            get {
                return ResourceManager.GetString("MainWindowRemoveAccountManifestConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can&apos;t remove accounts from the manifest file while it is encrypted..
        /// </summary>
        internal static string MainWindowRemoveAccountManifestEncrypted {
            get {
                return ResourceManager.GetString("MainWindowRemoveAccountManifestEncrypted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh account session.
        /// </summary>
        internal static string MainWindowSessionRefresh {
            get {
                return ResourceManager.GetString("MainWindowSessionRefresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your session has been refreshed..
        /// </summary>
        internal static string MainWindowSessionRefreshed {
            get {
                return ResourceManager.GetString("MainWindowSessionRefreshed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to refresh your session, try again soon..
        /// </summary>
        internal static string MainWindowSessionRefreshFailed {
            get {
                return ResourceManager.GetString("MainWindowSessionRefreshFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking for updates, please wait..
        /// </summary>
        internal static string MainWindowSetupCheckForUpdate {
            get {
                return ResourceManager.GetString("MainWindowSetupCheckForUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decrypting manifest, please wait..
        /// </summary>
        internal static string MainWindowSetupDecrypt {
            get {
                return ResourceManager.GetString("MainWindowSetupDecrypt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setting up main window, please wait..
        /// </summary>
        internal static string MainWindowSetupFirstTime {
            get {
                return ResourceManager.GetString("MainWindowSetupFirstTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Syncing time with Steam, please wait..
        /// </summary>
        internal static string MainWindowSetupSyncTime {
            get {
                return ResourceManager.GetString("MainWindowSetupSyncTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setting up the tray icon, please wait..
        /// </summary>
        internal static string MainWindowSetupTrayIcon {
            get {
                return ResourceManager.GetString("MainWindowSetupTrayIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} confirmations were accepted..
        /// </summary>
        internal static string MainWindowTradingNotificationAcceptedMany {
            get {
                return ResourceManager.GetString("MainWindowTradingNotificationAcceptedMany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A confirmation was accepted..
        /// </summary>
        internal static string MainWindowTradingNotificationAcceptedSingle {
            get {
                return ResourceManager.GetString("MainWindowTradingNotificationAcceptedSingle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accepted new confirmations.
        /// </summary>
        internal static string MainWindowTradingNotificationAcceptedTMany {
            get {
                return ResourceManager.GetString("MainWindowTradingNotificationAcceptedTMany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accepted a new confirmation.
        /// </summary>
        internal static string MainWindowTradingNotificationAcceptedTSingle {
            get {
                return ResourceManager.GetString("MainWindowTradingNotificationAcceptedTSingle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are {0} pending requests..
        /// </summary>
        internal static string MainWindowTradingNotificationPendingMany {
            get {
                return ResourceManager.GetString("MainWindowTradingNotificationPendingMany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is 1 pending request..
        /// </summary>
        internal static string MainWindowTradingNotificationPendingSingle {
            get {
                return ResourceManager.GetString("MainWindowTradingNotificationPendingSingle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pending confirmations.
        /// </summary>
        internal static string MainWindowTradingNotificationPendingTMany {
            get {
                return ResourceManager.GetString("MainWindowTradingNotificationPendingTMany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pending confirmation.
        /// </summary>
        internal static string MainWindowTradingNotificationPendingTSingle {
            get {
                return ResourceManager.GetString("MainWindowTradingNotificationPendingTSingle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add account.
        /// </summary>
        internal static string MainWindowUIAddAccount {
            get {
                return ResourceManager.GetString("MainWindowUIAddAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authenticator settings.
        /// </summary>
        internal static string MainWindowUIAuthenticatorSettings {
            get {
                return ResourceManager.GetString("MainWindowUIAuthenticatorSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse updates.
        /// </summary>
        internal static string MainWindowUIBrowseUpdates {
            get {
                return ResourceManager.GetString("MainWindowUIBrowseUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Developer.
        /// </summary>
        internal static string MainWindowUIDEV {
            get {
                return ResourceManager.GetString("MainWindowUIDEV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Crash&quot;.
        /// </summary>
        internal static string MainWindowUIDEVCrash {
            get {
                return ResourceManager.GetString("MainWindowUIDEVCrash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Force auto login.
        /// </summary>
        internal static string MainWindowUIDEVFAE {
            get {
                return ResourceManager.GetString("MainWindowUIDEVFAE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh manifest.
        /// </summary>
        internal static string MainWindowUIDEVRefreshManifest {
            get {
                return ResourceManager.GetString("MainWindowUIDEVRefreshManifest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show toast (error).
        /// </summary>
        internal static string MainWindowUIDEVToastE {
            get {
                return ResourceManager.GetString("MainWindowUIDEVToastE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show toast (info).
        /// </summary>
        internal static string MainWindowUIDEVToastI {
            get {
                return ResourceManager.GetString("MainWindowUIDEVToastI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encryption settings.
        /// </summary>
        internal static string MainWindowUIEncryptionSettings {
            get {
                return ResourceManager.GetString("MainWindowUIEncryptionSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import from Android.
        /// </summary>
        internal static string MainWindowUIImportAndroid {
            get {
                return ResourceManager.GetString("MainWindowUIImportAndroid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import maFile.
        /// </summary>
        internal static string MainWindowUIImportFile {
            get {
                return ResourceManager.GetString("MainWindowUIImportFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load accounts.
        /// </summary>
        internal static string MainWindowUILoadAccount {
            get {
                return ResourceManager.GetString("MainWindowUILoadAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string MainWindowUILogin {
            get {
                return ResourceManager.GetString("MainWindowUILogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quit.
        /// </summary>
        internal static string MainWindowUIQuit {
            get {
                return ResourceManager.GetString("MainWindowUIQuit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string MainWindowUISettings {
            get {
                return ResourceManager.GetString("MainWindowUISettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        internal static string MainWindowUIUpdateButton {
            get {
                return ResourceManager.GetString("MainWindowUIUpdateButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There&apos;s a new update available for Steam Authenticator..
        /// </summary>
        internal static string MainWindowUpdateFound {
            get {
                return ResourceManager.GetString("MainWindowUpdateFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New update available.
        /// </summary>
        internal static string MainWindowUpdateFoundT {
            get {
                return ResourceManager.GetString("MainWindowUpdateFoundT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was no new update found for Steam Authenticator..
        /// </summary>
        internal static string MainWindowUpdateNotFound {
            get {
                return ResourceManager.GetString("MainWindowUpdateNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No update found.
        /// </summary>
        internal static string MainWindowUpdateNotFoundT {
            get {
                return ResourceManager.GetString("MainWindowUpdateNotFoundT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter your encryption passkey..
        /// </summary>
        internal static string ManifestEnterKey {
            get {
                return ResourceManager.GetString("ManifestEnterKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to That passkey is invalid!.
        /// </summary>
        internal static string ManifestKeyInvalid {
            get {
                return ResourceManager.GetString("ManifestKeyInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a passkey below, or hit cancel to remain unencrypted..
        /// </summary>
        internal static string ManifestPropmptSetupKey {
            get {
                return ResourceManager.GetString("ManifestPropmptSetupKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have selected to not encrypt your files. If your maFile happen to be stolen anyone can get your auth codes..
        /// </summary>
        internal static string ManifestSetupCanceled {
            get {
                return ResourceManager.GetString("ManifestSetupCanceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notice.
        /// </summary>
        internal static string ManifestSetupCanceledT {
            get {
                return ResourceManager.GetString("ManifestSetupCanceledT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passkey successfully set..
        /// </summary>
        internal static string ManifestSetupComplete {
            get {
                return ResourceManager.GetString("ManifestSetupComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm new passkey..
        /// </summary>
        internal static string ManifestSetupConfirmKey {
            get {
                return ResourceManager.GetString("ManifestSetupConfirmKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passkey failed to set. Nothing has been encrypted..
        /// </summary>
        internal static string ManifestSetupFailed {
            get {
                return ResourceManager.GetString("ManifestSetupFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passkeys do not match!.
        /// </summary>
        internal static string ManifestSetupKeysDoNotMatch {
            get {
                return ResourceManager.GetString("ManifestSetupKeysDoNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatically unlock the security settings window.
        /// </summary>
        internal static string SecuritySettingsAutoUnlock {
            get {
                return ResourceManager.GetString("SecuritySettingsAutoUnlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When enabled this window is automatically unlocked and &apos;Save my password...&apos; is enabled..
        /// </summary>
        internal static string SecuritySettingsAutoUnlockH {
            get {
                return ResourceManager.GetString("SecuritySettingsAutoUnlockH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to change.
        /// </summary>
        internal static string SecuritySettingsChange {
            get {
                return ResourceManager.GetString("SecuritySettingsChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changing.
        /// </summary>
        internal static string SecuritySettingsChanging {
            get {
                return ResourceManager.GetString("SecuritySettingsChanging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm new passkey.
        /// </summary>
        internal static string SecuritySettingsConfirmNewPasskey {
            get {
                return ResourceManager.GetString("SecuritySettingsConfirmNewPasskey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New passkey.
        /// </summary>
        internal static string SecuritySettingsNewPasskey {
            get {
                return ResourceManager.GetString("SecuritySettingsNewPasskey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passkey incorrect!.
        /// </summary>
        internal static string SecuritySettingsPassIncorrect {
            get {
                return ResourceManager.GetString("SecuritySettingsPassIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update passkey.
        /// </summary>
        internal static string SecuritySettingsPasskeyButtonUpdate {
            get {
                return ResourceManager.GetString("SecuritySettingsPasskeyButtonUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passkeys do not match!.
        /// </summary>
        internal static string SecuritySettingsPasskeyDoNotMatch {
            get {
                return ResourceManager.GetString("SecuritySettingsPasskeyDoNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to {0} passkey!.
        /// </summary>
        internal static string SecuritySettingsProcessedFailedPasskey {
            get {
                return ResourceManager.GetString("SecuritySettingsProcessedFailedPasskey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} passkey, please wait....
        /// </summary>
        internal static string SecuritySettingsProcessingPasskey {
            get {
                return ResourceManager.GetString("SecuritySettingsProcessingPasskey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to remove.
        /// </summary>
        internal static string SecuritySettingsRemove {
            get {
                return ResourceManager.GetString("SecuritySettingsRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        internal static string SecuritySettingsRemoveBTN {
            get {
                return ResourceManager.GetString("SecuritySettingsRemoveBTN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passkey successfully removed..
        /// </summary>
        internal static string SecuritySettingsRemoved {
            get {
                return ResourceManager.GetString("SecuritySettingsRemoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removing.
        /// </summary>
        internal static string SecuritySettingsRemoving {
            get {
                return ResourceManager.GetString("SecuritySettingsRemoving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When enabled your password is remembered so that you do not have to enter it when Steam Authenticator opens.
        /// </summary>
        internal static string SecuritySettingsSavePasswodH {
            get {
                return ResourceManager.GetString("SecuritySettingsSavePasswodH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save my password with Windows Credential Locker.
        /// </summary>
        internal static string SecuritySettingsSavePassword {
            get {
                return ResourceManager.GetString("SecuritySettingsSavePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set passkey.
        /// </summary>
        internal static string SecuritySettingsSet {
            get {
                return ResourceManager.GetString("SecuritySettingsSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to remove passkey! {0}.
        /// </summary>
        internal static string SecuritySettingsUnableToRemove {
            get {
                return ResourceManager.GetString("SecuritySettingsUnableToRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update passkey.
        /// </summary>
        internal static string SecuritySettingsUpdate {
            get {
                return ResourceManager.GetString("SecuritySettingsUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Windows file encryption.
        /// </summary>
        internal static string SecuritySettingsUseWFE {
            get {
                return ResourceManager.GetString("SecuritySettingsUseWFE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Whether or not Windows file encryption is used to encrypt the maFile and manifest in addition to any other encryption methods.
        /// </summary>
        internal static string SecuritySettingsUseWFEH {
            get {
                return ResourceManager.GetString("SecuritySettingsUseWFEH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow beta builds.
        /// </summary>
        internal static string SettingsAllowBeta {
            get {
                return ResourceManager.GetString("SettingsAllowBeta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Include beta builds when searching for update.
        /// </summary>
        internal static string SettingsAllowBetaHelp {
            get {
                return ResourceManager.GetString("SettingsAllowBetaHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatically enter auth code when logging in.
        /// </summary>
        internal static string SettingsAutoEntry {
            get {
                return ResourceManager.GetString("SettingsAutoEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatically enter your Steam Guard code into the &quot;enter your auth code&quot; window.
        /// </summary>
        internal static string SettingsAutoEntryHelp {
            get {
                return ResourceManager.GetString("SettingsAutoEntryHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatically refresh account session on startup.
        /// </summary>
        internal static string SettingsAutoRefreshSession {
            get {
                return ResourceManager.GetString("SettingsAutoRefreshSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatically refresh your account sessions on startup.
        /// </summary>
        internal static string SettingsAutoRefreshSessionH {
            get {
                return ResourceManager.GetString("SettingsAutoRefreshSessionH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check for update on startup.
        /// </summary>
        internal static string SettingsCheckForUpdates {
            get {
                return ResourceManager.GetString("SettingsCheckForUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking interval (seconds).
        /// </summary>
        internal static string SettingsCheckingInterval {
            get {
                return ResourceManager.GetString("SettingsCheckingInterval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatically confirm market transactions.
        /// </summary>
        internal static string SettingsConfirmMarket {
            get {
                return ResourceManager.GetString("SettingsConfirmMarket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatically confirm trades.
        /// </summary>
        internal static string SettingsConfirmTrade {
            get {
                return ResourceManager.GetString("SettingsConfirmTrade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Periodically check accounts for confirmations.
        /// </summary>
        internal static string SettingsPeriodicallyCheck {
            get {
                return ResourceManager.GetString("SettingsPeriodicallyCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display search field.
        /// </summary>
        internal static string SettingsSearch {
            get {
                return ResourceManager.GetString("SettingsSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort accounts alphabetically.
        /// </summary>
        internal static string SettingsSortAlpha {
            get {
                return ResourceManager.GetString("SettingsSortAlpha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Store accounts in .maFiles.
        /// </summary>
        internal static string SettingsStoreMaFiles {
            get {
                return ResourceManager.GetString("SettingsStoreMaFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Whether or not account info is stored in files or using the Windows Credential Locker.
        /// </summary>
        internal static string SettingsStoreMaFilesHelp {
            get {
                return ResourceManager.GetString("SettingsStoreMaFilesHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wait, there are unsaved changes! Are you sure you want to leave and discard these changes?
        ///Yes - Leave and discard
        ///No - Save and leaveCancel - Dismiss this and go back.
        /// </summary>
        internal static string SettingsUnsaved {
            get {
                return ResourceManager.GetString("SettingsUnsaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discard unsaved changes?.
        /// </summary>
        internal static string SettingsUnsavedT {
            get {
                return ResourceManager.GetString("SettingsUnsavedT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use DPAPI to encrypt the manifest and maFiles.
        /// </summary>
        internal static string SettingsUseDPAPI {
            get {
                return ResourceManager.GetString("SettingsUseDPAPI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Whether or not DPAPI is used to encrypt the maFile and manifest in addition to any other encryption methods.
        /// </summary>
        internal static string SettingsUseDPAPIH {
            get {
                return ResourceManager.GetString("SettingsUseDPAPIH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accept.
        /// </summary>
        internal static string TradeAccept {
            get {
                return ResourceManager.GetString("TradeAccept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last refreshed at {0}.
        /// </summary>
        internal static string TradeCachedTime {
            get {
                return ResourceManager.GetString("TradeCachedTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deny.
        /// </summary>
        internal static string TradeDeny {
            get {
                return ResourceManager.GetString("TradeDeny", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last refreshed at {0}
        ///
        ///
        ///{1}
        ///Request made {2}.
        /// </summary>
        internal static string TradeDetails {
            get {
                return ResourceManager.GetString("TradeDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press again to accept..
        /// </summary>
        internal static string TradeDoubleAccept {
            get {
                return ResourceManager.GetString("TradeDoubleAccept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press again to deny..
        /// </summary>
        internal static string TradeDoubleDeny {
            get {
                return ResourceManager.GetString("TradeDoubleDeny", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generic confirmation from {0}.
        /// </summary>
        internal static string TradeGeneric {
            get {
                return ResourceManager.GetString("TradeGeneric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to refresh confirmations for {0}! Please try refreshing the session for this account.
        ///Error: {1}.
        /// </summary>
        internal static string TradeHandlerFailed {
            get {
                return ResourceManager.GetString("TradeHandlerFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to refresh confirmations for {0} (WGInvalidException)! Please try refreshing the session for this account..
        /// </summary>
        internal static string TradeHandlerWGInvalidException {
            get {
                return ResourceManager.GetString("TradeHandlerWGInvalidException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to refresh confirmations for {0} (WGTokenExpired)! Please try refreshing the session for this account..
        /// </summary>
        internal static string TradeHandlerWGTokenExpired {
            get {
                return ResourceManager.GetString("TradeHandlerWGTokenExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Market transaction from {0}.
        /// </summary>
        internal static string TradeMarket {
            get {
                return ResourceManager.GetString("TradeMarket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your account name: {0}
        ///ConfType: {1}
        ///Creator: {2}
        ///Description: {3}
        ///{4}
        ///Request made: {5}
        ///ID: {6}
        ///Key: {7}
        ///IntType: {8}
        ///Hash code: {9}.
        /// </summary>
        internal static string TradeMoreInfo {
            get {
                return ResourceManager.GetString("TradeMoreInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More info.
        /// </summary>
        internal static string TradeMoreInfoBTN {
            get {
                return ResourceManager.GetString("TradeMoreInfoBTN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ConfType: {1}
        ///Creator: {2}
        ///Description: {3}
        ///{4}
        ///Request made: {5}
        ///ID: {6}
        ///Key: {7}
        ///IntType: {8}
        ///Hash code: {9}.
        /// </summary>
        internal static string TradeMoreInfoNA {
            get {
                return ResourceManager.GetString("TradeMoreInfoNA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please wait....
        /// </summary>
        internal static string TradePleaseWait {
            get {
                return ResourceManager.GetString("TradePleaseWait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy the current auth code.
        /// </summary>
        internal static string TrayIconCopyCode {
            get {
                return ResourceManager.GetString("TrayIconCopyCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide.
        /// </summary>
        internal static string TrayIconHide {
            get {
                return ResourceManager.GetString("TrayIconHide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quit.
        /// </summary>
        internal static string TrayIconQuit {
            get {
                return ResourceManager.GetString("TrayIconQuit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore.
        /// </summary>
        internal static string TrayIconRestore {
            get {
                return ResourceManager.GetString("TrayIconRestore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View trades.
        /// </summary>
        internal static string TrayIconTrades {
            get {
                return ResourceManager.GetString("TrayIconTrades", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All accounts and settings have been imported! Press &quot;Ok&quot; to continue..
        /// </summary>
        internal static string WelcomeImportComplete {
            get {
                return ResourceManager.GetString("WelcomeImportComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Importation complete.
        /// </summary>
        internal static string WelcomeImportCompleteT {
            get {
                return ResourceManager.GetString("WelcomeImportCompleteT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import account(s) from a file.
        /// </summary>
        internal static string WelcomeImportFile {
            get {
                return ResourceManager.GetString("WelcomeImportFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import my account from my phone.
        /// </summary>
        internal static string WelcomeImportPhone {
            get {
                return ResourceManager.GetString("WelcomeImportPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to Steam Authenticator!.
        /// </summary>
        internal static string WelcomeLabel {
            get {
                return ResourceManager.GetString("WelcomeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This folder does not contain a manifest.json file or a maFile folder.
        ///Do you wish to use this folder?
        ///{0}.
        /// </summary>
        internal static string WelcomeNoManifest {
            get {
                return ResourceManager.GetString("WelcomeNoManifest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the folder of your old Steam Authenticator (or Steam Desktop Authenticator) install.
        /// </summary>
        internal static string WelcomeSelectFolder {
            get {
                return ResourceManager.GetString("WelcomeSelectFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign in to Steam.
        /// </summary>
        internal static string WelcomeSignIn {
            get {
                return ResourceManager.GetString("WelcomeSignIn", resourceCulture);
            }
        }
    }
}
